### ISSUE TITLE
Does not generate tailwind.css output file on building .net core project

### ISSUE THREAD

**Issue by zohaibcs** [MJRasicci/Tailwind.MSBuild#28]
@MJRasicci I have installed this package in my asp.net core project. It does generate all files on first builed. Then I update tailwind.config.js file and rebuild project but it does not update tailwind.css output file. 
I am not facing any error. Also cannot find any help online. TIA

**Comment by MJRasicci** [comment]
This was likely due to the path to the configurations files not being within quotes when passed in the CLI's argument list and a fix is included in v1.1, along with improved logging.
